name: release

on:
  push:
    tags:
      - "*"

env:
  IMAGE: dataesr/bso-ui

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: changelog-config.js
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          body: "${{ steps.changelog.outputs.changes }}"

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Login docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker build -t $IMAGE:latest -t $IMAGE:${{ steps.version.outputs.version }} .
      - name: Push image
        run: |
          docker push $IMAGE:latest
          docker push $IMAGE:${{ steps.version.outputs.version }}
      - name: Notify in Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"📦 New release <https://github.com/dataesr/bso-ui/releases/tag/${{ steps.version.outputs.version }}|${{ steps.version.outputs.version }}> in bso-ui"}' ${{ secrets.SLACK_WEBHOOK }}
